### ISSUE TITLE
Plaiceholder blurhash support

### ISSUE THREAD

**Issue by vlowe85** [WalkingPizza/strapi-plugin-placeholder#10]
Blurhash is supported by Plaiceholder, can it be a configuration option to use it?

The blurhash string is nicer to work with than base64

I hardcoded the change to use blurhash in this fork, it would be nicer as a config option - https://github.com/vlowe85/strapi-plugin-placeholder

**Comment by yasssuz** [comment]
Hello, please consider using https://market.strapi.io/plugins/strapi-blurhash
