### ISSUE TITLE
Support node v18

### ISSUE THREAD

**Issue by niklasfjeldberg** [WalkingPizza/strapi-plugin-placeholder#11]
Node v18 is the latest LTS version and should be supported. Currently you get an error about v16 being the latest supported version.

**Comment by Confuze** [comment]
It looks like it works fine with the lts version.
After lifting the engine requirements in package.json the plugin function as expected on v18.14.0

**Comment by eliascarella** [comment]
Any reason the change hasn't been made yet ?

**Comment by yasssuz** [comment]
@eliascarella @niklasfjeldberg 
Please, consider migrating to now version: https://github.com/WalkingPizza/strapi-plugin-placeholder/issues/14
