### ISSUE TITLE
Package is not maintaned, migration to continued version

### ISSUE THREAD

**Issue by yasssuz** [WalkingPizza/strapi-plugin-placeholder#14]
## strapi-plugin-placeholder-continued

As the original `strapi-plugin-placeholder` project is no longer maintained by its owner, I decided to create a new repository called `strapi-plugin-placeholder-continued`. This updated plugin includes fixes for the following issues that were left open in the previous project:
- Support for Node 18
- Errors during image replacement
- Placeholder field with value null after moving images

`strapi-plugin-placeholder-continued` is an active, evolving project that welcomes any issue reports and pull requests. Your contributions will help improve the plugin, and I'll be more than happy to review and merge updates.

Special thanks to @WalkingPizza for initially developing this project.
Looking forward in onboarding the current users to the new continued version.

Repository: https://github.com/yasssuz/strapi-plugin-placeholder-continued
Package: https://www.npmjs.com/package/strapi-plugin-placeholder-continued

**Comment by yasssuz** [comment]
I managed to become a trusted contributor on this repository, and from now on I'll be the one to mostly manage contributions, issues and enhancements.

**Comment by mauriciabad** [comment]
What happened with the new repository `strapi-plugin-placeholder-continued`? It got deleted
