### ISSUE TITLE
[Bug] Placeholder attribute set to null when changing image location

### ISSUE THREAD

**Issue by RilDev** [WalkingPizza/strapi-plugin-placeholder#6]
Hi there, thanks for this plugin, it is really handy!

## Bug Description

When uploading an image, a `placeholder` variable is set with a base64 string.
But when I change the location of the image --  when I put it in a folder --, the `placeholder` variable is set to `null`.

![image](https://user-images.githubusercontent.com/13135150/188802808-50fdc393-def6-44f2-b2c6-6cc99b612de3.png)

## Reproduction Steps

1) Upload an image into the media library
2) Check that the placeholder attribute is set correctly
3) Edit the image to change it's location
4) Check the image's placeholder attribute again

**Comment by aturkewi** [comment]
Yeah, I'm seeing this issue as well. On version `4.3.6`.

**Comment by nikravi** [comment]
Please review the PR which addresses this issue https://github.com/WalkingPizza/strapi-plugin-placeholder/pull/12
